      - name: Collect output
        run: |
          mkdir -p output
          find . -name "*.deb" -exec cp {} output/ \; || true
          find . -name "*.dylib" -exec cp {} output/ \; || true

      - name: Show output
        run: ls -R output

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Moustache-build
          path: output/
