name: Swift Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build info
        run: |
          mkdir output
          echo "Moustache build successful 🔥" > output/result.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: moustache-build
          path: output/
